### ISSUE TITLE
Create web api wrapper exposing the library functionalities

### ISSUE THREAD

**Issue by TotallyNotChase** [TotallyNotChase/glitch-this#11]
A fair number of people want this to be accessed through a webapi, so non-devs can have fun too. I'm totally in on that, I'd have already made one if I owned a domain.

But if anyone would like to implement a web api, go for it! The library should be of help, when you're done, I can link the api in the README

You can do it in your own repo (I'd really appreciate it if it was open source, free, and easy to use) and ask me anything if you need help!

**Comment by chrisiaut** [comment]
I'm thinking of including it as a filter on [PictShare](https://github.com/HaschekSolutions/pictshare) so it can be accessed as an API

**Comment by pahefu** [comment]
I didnt make one API, but ported the library methods to pure Javascript (no libs, just canvas) in the browser, plus made a live example on applying it on every frame from a HTML5 video while it's being played.

I guess it could be used in NodeJS too with some tweaks, for those who like to server pages/apis that way.

Not really sure on having ported the numpy code in a 100% true fashion but.. works for a first demo :P.

[Repo link](https://github.com/pahefu/web-glitch-this).

**Comment by TotallyNotChase** [comment]
@pahefu Awesome! Will link your repo on README!

Also, could you add normal image support as well, right now you can only glitch videos on the demo.

**Comment by pahefu** [comment]
Yeah, It works with images too (as long as you pass a Canvas pixel array data, the procedure is the same for the "library" part), so will just need to add the UI options on the demo html page.

**Comment by pahefu** [comment]
Updated the repo demo with the image-only processing.

Also now you can download a glitched image/frame in their original size, which makes this as close as possible to original lib, on the browser. Canvas resizing from css made right-click download scaled to the screen resolution.
