### ISSUE TITLE
Feature Request - Increase Glitch Level over a specified duration

### ISSUE THREAD

**Issue by tylerforesthauser** [TotallyNotChase/glitch-this#13]
Would you consider the ability to add some kind of glitch easing, so you can increase the glitch level over the duration of a gif?

**Comment by TotallyNotChase** [comment]
Will be working on this soon!

**Comment by TotallyNotChase** [comment]
@tylerforesthauser This is currently in the 'preview-release` branch, you can test it out [here](https://github.com/TotallyNotChase/glitch-this/tree/preview-release) if you'd like!

**Comment by TotallyNotChase** [comment]
Just rolled this out on v0.1.0 + a lot more! Check out the [docs](https://github.com/TotallyNotChase/glitch-this/wiki) for more info!
