### ISSUE TITLE
Add -o/--output to specify different output file

### ISSUE THREAD

**Issue by KopfKrieg** [TotallyNotChase/glitch-this#14]
I wanted to create multiple glitched images from a file when I found out there is no -o/--output parameter. Would be nice to have that (optional) parameter available for cases like, e.g., this:
```
for i in {0..10}
do
  glitch_this -c input.png 2
  mv glitched_input.png glitched_$i.png
done
```

**Comment by TotallyNotChase** [comment]
I see, do you mean a parameter specifying a full/relative path indicating where output image should be?

If so, I'll add this in 0.0.9 :)

**Comment by KopfKrieg** [comment]
Yep, that's what I meant. So I could write something like the following, which is also easily scriptable then:
```
glitch_this -c input.png 2 -o output.png
```

**Comment by TotallyNotChase** [comment]
@KopfKrieg v0.0.9 has this + much more, check out the [changelog](https://github.com/TotallyNotChase/glitch-this/blob/master/CHANGELOG.md)!
