### ISSUE TITLE
KeyError : 'duration'

### ISSUE THREAD

**Issue by siu3334** [TotallyNotChase/glitch-this#32]
Hi,
The glitch_this command works well with most gifs, but it is particularly throwing error with this gif:
![Discord Avatar](https://cdn.discordapp.com/avatars/713232390549667952/a_cd5b8486534685138219cb64c8638ff3.gif?size=1024)

The error:
```py
root:~ # glitch_this ./avatar.gif -g -ig 2
Traceback (most recent call last):
  File "/usr/local/bin/glitch_this", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/glitch_this/commandline.py", line 176, in main
    step=args.step)
  File "/usr/local/lib/python3.7/dist-packages/glitch_this/glitch_this.py", line 330, in glitch_gif
    duration += frame.info['duration']
KeyError: 'duration'
```

**Comment by TotallyNotChase** [comment]
It seems like PIL/pillow can't extract the duration info from each frame on this gif. Unfortunately, there are some gifs that don't provide all the information required to PIL/pillow

**Comment by siu3334** [comment]
Any way you can catch the exception to make error user friendly?

**Comment by TotallyNotChase** [comment]
Sure, updated to 1.0.1
