### ISSUE TITLE
Glitched Version Number

### ISSUE THREAD

**Issue by MyCatCondo** [TotallyNotChase/glitch-this#34]
`Current version: 1.0.2 | Latest version: 1.0.1`
`A new version of "glitch-this" is available. Please consider upgrading via pip3 install --upgrade glitch-this`

**Comment by TotallyNotChase** [comment]
That's weird, this doesn't happen for me - even after re-installing. This should **only** happen if upstream (pypi) has a lower version than the one you have. But pypi should have 1.0.2

**Comment by TotallyNotChase** [comment]
Could you try reinstalling after removing the `version.info` file in the `glitch_this` package directory? Uninstall doesn't remove that file, so it might be causing cache issues. Otherwise, It'll fix itself the next time it checks upstream

**Comment by MyCatCondo** [comment]
Deleted `version.info` and its not complaining anymore. Thanks :)
I'm going to close this issue now
