### ISSUE TITLE
Strange dot patterns on GIFs

### ISSUE THREAD

**Issue by skyrover7** [TotallyNotChase/glitch-this#35]
I am glitching some 500 x 500 images with plain backgrounds.

However I am noticing that the backgrounds are getting some strange dot patterns on them. Any ideas on why this is happening? You can see the original image and output gif below. 

Settings are pretty standard
* color offset `true`
* scan lines `false`
* duration `150`
* glitch level `2`
* loops `0` (infinite)

![23](https://user-images.githubusercontent.com/42014195/132463959-a4597471-811a-4571-9c66-b8ea8d011c0b.png)
![23](https://user-images.githubusercontent.com/42014195/132463960-4043b5f4-18d3-494d-9e6e-3340e302cca9.gif)

**Comment by TotallyNotChase** [comment]
Hmm, I can't seem to be able to reproduce this. I ran ` glitch_this test.png 2 -c -g -d 180`. Where test.png is the original image you uploaded.

This is the result I get from that-
![glitched_test](https://user-images.githubusercontent.com/44284917/132500207-330641b6-a7ee-46aa-8bf1-026810e9e916.gif)

Here's a full demonstration for clarity-

https://user-images.githubusercontent.com/44284917/132501443-d65e8861-a8b4-4255-95d7-284c1567b0c5.mp4

Could you tell me a bit more about the OS and glitch-this version you're using? I've tried with `glitch-this==1.0.2` on windows and linux.

**Comment by skyrover7** [comment]
Appreciate the response! Turns out there was an additional image conversion in my code which was throwing stuff off. I removed that and it's working perfectly. thanks! You can mark this invalid if you like 😏
