### ISSUE TITLE
glitch_this.py uses global variables and has no main() function

### ISSUE THREAD

**Issue by KopfKrieg** [TotallyNotChase/glitch-this#6]
Just wanted to let you know that your glitch_this.py in your root folder doesn't have a main()-function and uses global variables. Personally I'd rewrite this using a main() function and move everything from global to local variables (which is, I have to admit, not that easy here. Creating a class might be a solution here).

And thank you for that project! It's really cool :)

**Comment by TotallyNotChase** [comment]
That is a bit intentional yes, I think it's fine without a main function and global vars since it's a script. 

The whole reason I made the variables global in the script is for the ease of use. I do care about enclosing them however, which is why they are enclosed in the `library` :)

**Comment by retr0h** [comment]
Out of curiosity, why isn't this package shipping with an executable?  Pip installing this package then having to python `./3.7.6/lib/python3.7/site-packages/glitch_this/glitch_this.py` is somewhat convoluted.

**Comment by tomplex** [comment]
@TotallyNotChase why doesn't the script use the library? The code is basically copied and pasted when it could just use the class in the library, thereby avoiding the items raised in this issue.

**Comment by TotallyNotChase** [comment]
I originally did not add the library since the script was supposed to be standalone, as I didn't have the library on pypi. But now I do and I might consider adding the library in the requirements.

**Comment by TotallyNotChase** [comment]
@tomplex @retr0h @KopfKrieg All caught up! the commandline script now comes with the library and is all cleaned up :)
