### ISSUE TITLE
Allow more glitch levels (or maybe floats for levels?)

### ISSUE THREAD

**Issue by KopfKrieg** [TotallyNotChase/glitch-this#7]
Just a suggestion for an enhancement: Currently there are only glitch levels between 1 and 10 allowed, but I miss a setting somewhere between 1 and 2. This could be solved by either allowing floats for glitch levels (not sure if the algorithm used can work with floats), or by doubling the number of levels by using a range from 1 to 20 instead of 1 to 10.

**Comment by TotallyNotChase** [comment]
@KopfKrieg Just added this in `0.1.3`! You can now use *floats* between 1.0 and 10.0 as `glitch_amount`! **Single or double digit precision** works best with this. Check out the [docs](https://github.com/TotallyNotChase/glitch-this/wiki) for more info!

**Increment/Decrement** (aka `glitch_change`) will also receive support for floats shortly. Should be done by tomorrow, stay tuned :)

P.S - Sorry for taking so long, I had exams and had to postpone development

**Comment by TotallyNotChase** [comment]
Alright, `glitch_amount` can now be in range 0.1 to 10.0 and increment/decrement (aka `glitch_change`) also supports floats! Check out `0.1.4`!

**Comment by KopfKrieg** [comment]
Cool, thank you :)
