### ISSUE TITLE
Add support for glitching gifs

### ISSUE THREAD

**Issue by EnderShadow** [TotallyNotChase/glitch-this#9]
It would be cool if you could input a gif and glitch it.

**Comment by TotallyNotChase** [comment]
Working on it! This will add support for GIFs in the script, but not the class. The library should be left modular.

There will be examples in `test_script.py` as to how one can use the library to glitch GIFs into GIFs though

**Comment by TotallyNotChase** [comment]
@EnderShadow Just added in v0.0.8! Now you can glitch GIFs using `glitch_gif` + you can also pass in `Image` objects instead of path now! 

Check it out and let me know if you encounter any bugs!
